package com.example.sdorica.domain;

public class Character {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.position
     *
     * @mbggenerated
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.have
     *
     * @mbggenerated
     */
    private Integer have;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_1
     *
     * @mbggenerated
     */
    private String skill1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_2
     *
     * @mbggenerated
     */
    private String skill2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_3
     *
     * @mbggenerated
     */
    private String skill3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_4
     *
     * @mbggenerated
     */
    private String skill4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_6
     *
     * @mbggenerated
     */
    private String skill6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_p
     *
     * @mbggenerated
     */
    private String skillP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skill_a
     *
     * @mbggenerated
     */
    private String skillA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.id
     *
     * @return the value of character.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.id
     *
     * @param id the value for character.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.name
     *
     * @return the value of character.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.name
     *
     * @param name the value for character.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.position
     *
     * @return the value of character.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.position
     *
     * @param position the value for character.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.have
     *
     * @return the value of character.have
     *
     * @mbggenerated
     */
    public Integer getHave() {
        return have;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.have
     *
     * @param have the value for character.have
     *
     * @mbggenerated
     */
    public void setHave(Integer have) {
        this.have = have;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_1
     *
     * @return the value of character.skill_1
     *
     * @mbggenerated
     */
    public String getSkill1() {
        return skill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_1
     *
     * @param skill1 the value for character.skill_1
     *
     * @mbggenerated
     */
    public void setSkill1(String skill1) {
        this.skill1 = skill1 == null ? null : skill1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_2
     *
     * @return the value of character.skill_2
     *
     * @mbggenerated
     */
    public String getSkill2() {
        return skill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_2
     *
     * @param skill2 the value for character.skill_2
     *
     * @mbggenerated
     */
    public void setSkill2(String skill2) {
        this.skill2 = skill2 == null ? null : skill2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_3
     *
     * @return the value of character.skill_3
     *
     * @mbggenerated
     */
    public String getSkill3() {
        return skill3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_3
     *
     * @param skill3 the value for character.skill_3
     *
     * @mbggenerated
     */
    public void setSkill3(String skill3) {
        this.skill3 = skill3 == null ? null : skill3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_4
     *
     * @return the value of character.skill_4
     *
     * @mbggenerated
     */
    public String getSkill4() {
        return skill4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_4
     *
     * @param skill4 the value for character.skill_4
     *
     * @mbggenerated
     */
    public void setSkill4(String skill4) {
        this.skill4 = skill4 == null ? null : skill4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_6
     *
     * @return the value of character.skill_6
     *
     * @mbggenerated
     */
    public String getSkill6() {
        return skill6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_6
     *
     * @param skill6 the value for character.skill_6
     *
     * @mbggenerated
     */
    public void setSkill6(String skill6) {
        this.skill6 = skill6 == null ? null : skill6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_p
     *
     * @return the value of character.skill_p
     *
     * @mbggenerated
     */
    public String getSkillP() {
        return skillP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_p
     *
     * @param skillP the value for character.skill_p
     *
     * @mbggenerated
     */
    public void setSkillP(String skillP) {
        this.skillP = skillP == null ? null : skillP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skill_a
     *
     * @return the value of character.skill_a
     *
     * @mbggenerated
     */
    public String getSkillA() {
        return skillA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skill_a
     *
     * @param skillA the value for character.skill_a
     *
     * @mbggenerated
     */
    public void setSkillA(String skillA) {
        this.skillA = skillA == null ? null : skillA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.label
     *
     * @return the value of character.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.label
     *
     * @param label the value for character.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}