package com.example.sdorica.dao;

import java.util.List;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    int insert(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    int insertSelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    Character selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Character record);

    List<Character> allCharacter();

    List<Character> characterOfName(String Name);

    List<Character> characterOfPosition(String position);

    List<Character> characterOfSearch(String from, String keyword);

    List<Character> characterOfSearchAll(String keyword);
}